#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""This module defines a hand in order to engage with a dice"""

from guess import dice

class DiceHand:
    """Represents a dice hand"""
    def __init__(self):
        """Initialize the dice hand object"""
        self.dice = dice.Dice()
        self.roll_history = []
        self.last_roll = None

    def roll_dice(self):
        """Roll the dice in hand"""
        self.dice.roll_dice()
        self.last_roll = self.dice.get_last_roll()
        self.roll_history.append(self.last_roll)

    def get_last_roll(self):
        """Return the value of the last die throw"""  
        return self.last_roll

    def get_roll_history(self):
        """Return all rolls from current session"""
        return self.roll_history
